#creates a db within the db folder


default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: db/docs_development.sqlite3

test: &test
  <<: *default
  database: db/docs_test.sqlite3

production:
